### ISSUE TITLE
Microdata not working

### ISSUE THREAD

**Issue by bmelman** [Interactivated/kiyoh_magento1#13]
https://{$server}/v1/publication/review/external/location/statistics?locationId= seems to have been replaced by https://www.kiyoh.com/v1/review/feed.xml?hash= 

(this is the only link i can find in the merchant portal)

**Comment by cowoder** [comment]
That's the xml feed, the module uses the api. If it's not working you might be using the feed hash instead of the api hash.

Xml feed hash: kiyoh account -> publish -> extra options.
Api hash: kiyoh account -> invites -> extra options.

**Comment by bmelman** [comment]
Found it! Works fine with the api hash

Kiyoh migratie pakket Dashboard seems to be lacking some/any api documentation
